const EventName = {
	REGISTRATION: {
		REGISTER_REQUEST: "REGISTER_REQUEST",
		REGISTER_SUCCESS: "REGISTER_SUCCESS",
		REGISTER_FAILURE: "REGISTER_FAILURE",
	},
	USER_ACCOUNT: {
        CHECK_AUTORISATION: "CHECK_AUTORISATION",
	}
};

export default EventName;