const REGISTRATION = {
    REGISTER_REQUEST: "REGISTER_REQUEST",
    REGISTER_SUCCESS: "REGISTER_SUCCESS",
    REGISTER_FAIL: "REGISTER_FAIL",
};

const AUTORISATION = {
    AUTORISATION_REQUEST: "AUTORISATION_REQUEST",
    AUTORISATION_SUCCESS: "AUTORISATION_SUCCESS",
    AUTORISATION_FAIL: "AUTORISATION_FAIL",
};

const TEST = {
    ADD_TEST: "ADD_TEST",
    DELETE_TEST: "DELETE_TEST",
    EDIT_TEST: "EDIT_TEST"
};

const TEACHER_PANEL = {
    OPEN_EDIT_TEST_MODAL: "OPEN_EDIT_TEST_MODAL",
    CLOSE_EDIT_TEST_MODAL: "CLOSE_EDIT_TEST_MODAL"
};


export {REGISTRATION, AUTORISATION, TEST, TEACHER_PANEL}