const EventName = {
    REGISTRATION: {
        REGISTER_REQUEST: "REGISTER_REQUEST",
        REGISTER_SUCCESS: "REGISTER_SUCCESS",
        REGISTER_FAILURE: "REGISTER_FAILURE",
    },
    USER_ACCOUNT: {
        CHECK_AUTORISATION: "CHECK_AUTORISATION",
    },
    LOADING: {
        LOADING_START: "LOADING_START",
        LOADING_STOP: "LOADING_STOP",
    },
    TEST: {
        ADD_TEST: "ADD_TEST",
        DELETE_TEST: "DELETE_TEST"
    }
};

export default EventName;